language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_install:
  - composer self-update
  - composer validate

install:
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpspec run
